### ISSUE TITLE
Unexpected 'end of file during packet'

### ISSUE THREAD

**Issue by antage** [japaric/itm#14]
I often get error 'end of file during packet' while I run `itmdump -f itm.fifo -F`. It occurs because `itmdump` reads header but it can't read a full packet (receiving of the packet is in progress).

I think when `itmdump` invoked with `--follow` option it must never throw this error. It should retry reading   until it will read full packet.

**Comment by jmesmon** [comment]
I've observed this as well on some systems but not others.

Agreed that this shouldn't be a fatal error durring follow.

**Comment by birkenfeld** [comment]
I'm seeing this every time a panic message is written via `panic-itm`.

**Comment by jmesmon** [comment]
FWIW: It appears that using a real fifo (ie: `mkfifo`) allows follow to work more reliably for me, but that isn't ideal for all use cases.

**Comment by japaric** [comment]
I believe this was fixed in #17. If you are still encountering this problem let us know!
